version: 2

sphinx:
  builder: html
  configuration: doc/conf.py

formats: all

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .[docs]
