version: 2

sphinx:
  builder: html
  configuration: doc/conf.py

formats: all

submodules:
  include: all
  recursive: true

python:
  version: "3.8"
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .[docs]
